M48
; DRILL file {KiCad (7.0.0)} date Thu Aug 31 15:40:21 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-31T15:40:21+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.220
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X130.31Y-88.01
T2
X118.448Y-87.01
X118.448Y-116.51
X186.448Y-87.01
X186.448Y-116.51
T0
M30
